INSERT INTO CUADERNO (NOMBRE,TIPO) VALUES ('CUADERNO1','RAYAS');
INSERT INTO CUADERNO (NOMBRE,TIPO) VALUES ('CUADERNO2','CUADRICULA');
INSERT INTO CUADERNO (NOMBRE,TIPO) VALUES ('CUADERNO3', 'BLANCO');
INSERT INTO CUADERNO (NOMBRE,TIPO) VALUES ('CUADERNO4','PUNTEADO');
