INSERT INTO ARBOL (NOMBRE) VALUES ('Pino');
INSERT INTO ARBOL (NOMBRE) VALUES ('Cerezo');
INSERT INTO ARBOL (NOMBRE) VALUES ('Abeto');
INSERT INTO ARBOL (NOMBRE) VALUES ('Roble');
INSERT INTO ARBOL (NOMBRE) VALUES ('Arce');
