INSERT INTO ARCHIVADOR (MARCA) VALUES ('AbalitosSL');
INSERT INTO ARCHIVADOR (MARCA) VALUES ('ChistorrisSLU');
INSERT INTO ARCHIVADOR (MARCA) VALUES ('CerdinSA');
INSERT INTO ARCHIVADOR (MARCA) VALUES ('PedritoSM');